// @ts-check
import antfu from "@antfu/eslint-config";
import nextPlugin from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";

// Next.js core-web-vitals rules are lost when migrating off `next lint`.
// Re-surface every recommended Next rule as advisory ("warn"), web-only.
const nextRulesAsWarn = Object.fromEntries(
	Object.keys({
		...nextPlugin.configs.recommended?.rules,
		...nextPlugin.configs["core-web-vitals"]?.rules,
	}).map(rule => [rule, "warn"]),
);

export default antfu(
	{
		type: "app",
		typescript: true,
		react: true,

		// Project house style (user-specified). antfu formats via ESLint Stylistic
		// — no Prettier. `eslint . --fix` applies these repo-wide.
		stylistic: {
			indent: "tab",
			quotes: "double",
			semi: true,
			braceStyle: "1tbs",
		},

		// No Prettier-backed formatters (would touch CSS/MD); markdown off so the
		// protected docs (docs/PRODUCT.md, docs/DESIGN.md) are never reformatted.
		formatters: false,
		markdown: false,

		ignores: [
			"**/.next/**",
			"**/dist/**",
			"supabase/**",
			"docs/**",
			"specs/**",
			"**/database.types.ts", // generated by `bun run db:types`
			"index.ts", // root bun scaffold file
		],
	},

	// ── Mandatory project correctness rules (CONVENTIONS §1) — kept as errors ──
	// antfu exposes typescript-eslint rules under the `ts/` prefix.
	{
		name: "project/mandatory-rules",
		files: ["**/*.{ts,tsx,mts,cts}"],
		rules: {
			"ts/no-explicit-any": "error",
			"ts/no-non-null-assertion": "error",
			"ts/ban-ts-comment": [
				"error",
				{
					"ts-ignore": true,
					"ts-expect-error": "allow-with-description",
					"minimumDescriptionLength": 10,
				},
			],
			"ts/explicit-module-boundary-types": "error",
			"ts/consistent-type-imports": [
				"error",
				{ prefer: "type-imports", fixStyle: "inline-type-imports" },
			],
		},
	},

	// ── Disable auto-fixes that change types/semantics (Bun + Express + TS) ──
	// These rules are otherwise fine, but their --fix rewrites drop type info or
	// break module-type identity in this stack. Turned off (not "warn", which
	// would still auto-fix) to keep `eslint --fix` a pure formatter here.
	{
		name: "project/safe-autofix",
		files: ["**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}"],
		rules: {
			// 'http' and 'node:http' resolve to different type defs under Bun, so
			// converting breaks the Server type handed to shutdown.ts.
			"unicorn/prefer-node-protocol": "off",
			// Array<T>(n) → new Array → Array.from({length}) drops the element type
			// (unknown[]); keep the author's typed Array form.
			"unicorn/new-for-builtins": "off",
			// Array.from({length}, cb) → Array.from({length}).fill() drops the type.
			"e18e/prefer-array-fill": "off",
		},
	},

	// ── Relax antfu opinions that are not correctness issues in this repo ──
	// Off (not merely unfixed) so `eslint .` reaches zero errors without mass
	// non-behavioral churn. Genuine correctness rules stay enabled.
	{
		name: "project/relax-opinions",
		files: ["**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}"],
		rules: {
			// Compact one-liners and nested ternaries are house style here.
			"style/max-statements-per-line": "off",
			"style/multiline-ternary": "off",
			// Hoisted-function-before-use is intentional and TS-safe.
			"ts/no-use-before-define": "off",
			// `export const X = {...}` + `export type X` companion pattern is valid.
			"ts/no-redeclare": "off",
			// process/Buffer are ambient globals in this Bun/Node runtime.
			"node/prefer-global/process": "off",
			"node/prefer-global/buffer": "off",
			// Files export a component plus colocated helpers by design (DX hint).
			"react-refresh/only-export-components": "off",
			// React-Compiler optimization hint; this project doesn't use it.
			"react/unsupported-syntax": "off",
			// Defer to the official eslint-plugin-react-hooks (configured below).
			"react/rules-of-hooks": "off",
			"react/exhaustive-deps": "off",
			// Intentional blocking confirm() before discarding offline reviews.
			"no-alert": "off",
			// Intentional top-level await in the Bun server entrypoint.
			"antfu/no-top-level-await": "off",
			// Allow intentional irregular whitespace in strings/templates/JSX text:
			// Japanese content + a zero-width-space screen-reader re-announce trick.
			"no-irregular-whitespace": ["error", {
				skipStrings: true,
				skipTemplates: true,
				skipComments: true,
				skipJSXText: true,
			}],
		},
	},

	// ── Test files: permit testing conveniences ──
	{
		name: "project/test-files",
		// Covers both Bun test files (`*.test.ts`, `tests/`) and the web
		// Vitest infrastructure (`apps/web/test/**`: factories, MSW handlers,
		// the axe helper). Factories use casts to land on the shared-types
		// wire shape; non-null assertions are an everyday convenience inside
		// assertions.
		files: [
			"**/*.test.{ts,tsx}",
			"**/tests/**/*.ts",
			"**/test/**/*.{ts,tsx}",
		],
		rules: {
			"ts/no-non-null-assertion": "off",
			"ts/no-explicit-any": "off",
			"ts/consistent-type-imports": "off",
			// Test setup / fixture factories use top-level `vi.mock(...)`,
			// `expect.extend(...)`, and arrow-function returns; explicit
			// boundary types add noise without correctness gain.
			"ts/explicit-module-boundary-types": "off",
		},
	},

	// ── React hooks (official plugin; antfu v9 does not register it) ──
	{
		name: "project/react-hooks",
		files: ["**/*.{ts,tsx}"],
		plugins: { "react-hooks": reactHooks },
		rules: {
			"react-hooks/rules-of-hooks": "error",
			"react-hooks/exhaustive-deps": "warn",
		},
	},

	// ── Next.js advisory rules (web only) ──
	{
		name: "project/next",
		files: ["apps/web/**/*.{ts,tsx}"],
		plugins: { "@next/next": nextPlugin },
		rules: nextRulesAsWarn,
	},
);
