// @ts-check
import antfu from "@antfu/eslint-config";
import nextPlugin from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";

// Next.js core-web-vitals rules are lost when migrating off `next lint`.
// Re-surface every recommended Next rule as advisory ("warn"), web-only.
const nextRulesAsWarn = Object.fromEntries(
  Object.keys({
    ...nextPlugin.configs.recommended?.rules,
    ...nextPlugin.configs["core-web-vitals"]?.rules,
  }).map(rule => [rule, "warn"]),
);

export default antfu(
  {
    type: "app",
    typescript: true,
    react: true,

    // Project house style (user-specified). antfu formats via ESLint Stylistic
    // — no Prettier. `eslint . --fix` applies these repo-wide.
    stylistic: {
      indent: "tab",
      quotes: "double",
      semi: true,
      braceStyle: "1tbs",
    },

    // No Prettier-backed formatters (would touch CSS/MD); markdown off so the
    // protected docs (docs/PRODUCT.md, docs/DESIGN.md) are never reformatted.
    formatters: false,
    markdown: false,

    ignores: [
      "**/.next/**",
      "**/dist/**",
      "supabase/**",
      "docs/**",
      "specs/**",
      "**/database.types.ts", // generated by `bun run db:types`
      "index.ts", // root bun scaffold file
    ],
  },

  // ── Mandatory project correctness rules (CONVENTIONS §1) — kept as errors ──
  // antfu exposes typescript-eslint rules under the `ts/` prefix.
  {
    name: "project/mandatory-rules",
    files: ["**/*.{ts,tsx,mts,cts}"],
    rules: {
      "ts/no-explicit-any": "error",
      "ts/no-non-null-assertion": "error",
      "ts/ban-ts-comment": [
        "error",
        {
          "ts-ignore": true,
          "ts-expect-error": "allow-with-description",
          "minimumDescriptionLength": 10,
        },
      ],
      "ts/explicit-module-boundary-types": "error",
      "ts/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
    },
  },

  // ── React hooks (official plugin; antfu v9 does not register it) ──
  {
    name: "project/react-hooks",
    files: ["**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  // ── Next.js advisory rules (web only) ──
  {
    name: "project/next",
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: { "@next/next": nextPlugin },
    rules: nextRulesAsWarn,
  },
);
