/**
 * Zod schemas for the `fields_data` JSONB column on `cards` and the small
 * content shapes nested inside it. These cross the API → web wire so they
 * need runtime validation; the TS types live alongside as `z.infer` aliases
 * (see field-shapes.ts).
 */

import { z } from 'zod'

export const ExampleSentenceSchema = z.object({
  ja:            z.string(),
  en:            z.string(),
  furigana:      z.string(),
})

export const KanjiBreakdownSchema = z.object({
  kanji:   z.string(),
  radical: z.string(),
  meaning: z.string(),
  reading: z.string(),
})

/** Common base for vocabulary and grammar layouts. */
export const WordFieldsSchema = z.object({
  word:           z.string(),
  reading:        z.string(),
  meaning:        z.string(),
  partOfSpeech:   z.string().nullable().optional(),
  frequencyRank:  z.number().nullable().optional(),
  // Mnemonic is generated by AI (`generateCard` and the standalone
  // `generateMnemonic` endpoint) and persisted in `fields_data`. Must be
  // declared on the schema or Zod's default `.parse()` strips it from
  // every API response on the wire.
  mnemonic:       z.string().nullable().optional(),
  // ─── Lapis-style fields (Backend Completion Plan, Stage 1) ──────────────
  // Schema admission only. The AI generator (Stage 2) and the v4 review-
  // surface UI populate these. The DB CHECK constraint
  // `cards_fields_data_shape` enforces required keys only, so additive
  // shape changes do not require a migration.
  //
  // URL to a hosted image illustrating the word.
  picture:         z.string().nullable().optional(),
  // Integer mora position (0 = heiban / flat; 1..N = drop after Nth mora).
  // Drives the mora-line pitch graph. Coexists with the free-form
  // `pitchAccent` string on VocabularyFieldsDataSchema.
  pitchPosition:   z.number().int().nonnegative().nullable().optional(),
  // Short AI-authored prose covering register, connotation, or synonym
  // distinctions. First tab on the back of the v4 card.
  nuance:          z.string().nullable().optional(),
})

export const VocabularyFieldsDataSchema = WordFieldsSchema.extend({
  exampleSentences: z.array(ExampleSentenceSchema).optional(),
  kanjiBreakdown:   z.array(KanjiBreakdownSchema).optional(),
  pitchAccent:      z.string().nullable().optional(),
})

export const GrammarFieldsDataSchema = WordFieldsSchema.extend({
  exampleSentences: z.array(ExampleSentenceSchema).optional(),
})

/**
 * One token in a sentence breakdown — e.g. `{ token: '猫', reading: 'ねこ',
 * meaning: 'cat' }`. Powers the sentence-layout card's word-by-word
 * annotation strip. Reading and meaning are optional because particles
 * and punctuation tokens often need no annotation.
 */
export const SentenceBreakdownTokenSchema = z.object({
  token:   z.string(),
  reading: z.string().nullable().optional(),
  meaning: z.string().nullable().optional(),
})

/**
 * Concrete shape for `layout_type = 'sentence'` cards. Locked in by
 * Backend Completion Plan Stage 12 — `SentenceFieldsDataSchema` was an
 * open record (`z.record(z.string(), z.unknown())`) before this change,
 * "reserved for future use". The matching DB CHECK constraint enforces
 * `ja`, `en`, and `furigana` presence at the JSONB layer; the optional
 * keys below are validated only at parse time.
 */
export const SentenceFieldsDataSchema = z.object({
  /** Japanese sentence in kanji + kana (the front of the card). */
  ja:        z.string(),
  /** English gloss / translation (the back of the card). */
  en:        z.string(),
  /** Hiragana annotation for the kanji in `ja` (used by `<FuriganaText>`). */
  furigana:  z.string(),
  /** Optional per-token annotation strip for word-by-word breakdown UIs. */
  breakdown: z.array(SentenceBreakdownTokenSchema).nullable().optional(),
  /**
   * Optional AI-authored prose on register, pragmatics, or what makes the
   * sentence noteworthy. Mirrors `WordFieldsSchema.nuance` so the v4
   * review surface can render the same "nuance" tab regardless of layout.
   */
  nuance:    z.string().nullable().optional(),
})

/**
 * Wire-format `fields_data` — a union by layout_type. The DB CHECK constraint
 * `cards_fields_data_shape` enforces vocabulary/grammar carry the WordFields
 * keys, so the union is non-discriminated at the JSON level (the discriminator
 * lives on the parent card's `layoutType`).
 */
export const FieldsDataSchema = z.union([
  VocabularyFieldsDataSchema,
  GrammarFieldsDataSchema,
  SentenceFieldsDataSchema,
])
