/**
 * Zod schemas for the `fields_data` JSONB column on `cards` and the small
 * content shapes nested inside it. These cross the API → web wire so they
 * need runtime validation; the TS types live alongside as `z.infer` aliases
 * (see field-shapes.ts).
 */

import { z } from 'zod'

export const ExampleSentenceSchema = z.object({
  ja:            z.string(),
  en:            z.string(),
  furigana:      z.string(),
  // Lapis-style sentence-level asset. URL to a hosted audio clip of the
  // sentence; left as a plain string (not z.string().url()) so authoring
  // tools and frontends can use relative paths or data URIs during dev.
  sentenceAudio: z.string().nullable().optional(),
})

export const KanjiBreakdownSchema = z.object({
  kanji:   z.string(),
  radical: z.string(),
  meaning: z.string(),
  reading: z.string(),
})

/** Common base for vocabulary and grammar layouts. */
export const WordFieldsSchema = z.object({
  word:           z.string(),
  reading:        z.string(),
  meaning:        z.string(),
  partOfSpeech:   z.string().nullable().optional(),
  frequencyRank:  z.number().nullable().optional(),
  // Mnemonic is generated by AI (`generateCard` and the standalone
  // `generateMnemonic` endpoint) and persisted in `fields_data`. Must be
  // declared on the schema or Zod's default `.parse()` strips it from
  // every API response on the wire.
  mnemonic:       z.string().nullable().optional(),
  // ─── Lapis-style fields (Backend Completion Plan, Stage 1) ──────────────
  // Schema admission only. The AI generator (Stage 2) and the v4 review-
  // surface UI populate these. The DB CHECK constraint
  // `cards_fields_data_shape` enforces required keys only, so additive
  // shape changes do not require a migration.
  //
  // URL to a hosted image illustrating the word.
  picture:         z.string().nullable().optional(),
  // URL to a hosted audio clip of the expression itself.
  expressionAudio: z.string().nullable().optional(),
  // Integer mora position (0 = heiban / flat; 1..N = drop after Nth mora).
  // Drives the mora-line pitch graph. Coexists with the free-form
  // `pitchAccent` string on VocabularyFieldsDataSchema.
  pitchPosition:   z.number().int().nonnegative().nullable().optional(),
  // Short AI-authored prose covering register, connotation, or synonym
  // distinctions. First tab on the back of the v4 card.
  nuance:          z.string().nullable().optional(),
})

export const VocabularyFieldsDataSchema = WordFieldsSchema.extend({
  exampleSentences: z.array(ExampleSentenceSchema).optional(),
  kanjiBreakdown:   z.array(KanjiBreakdownSchema).optional(),
  pitchAccent:      z.string().nullable().optional(),
  collocations:     z.array(z.string()).optional(),
  homophones:       z.array(z.string()).optional(),
})

export const GrammarFieldsDataSchema = WordFieldsSchema.extend({
  exampleSentences: z.array(ExampleSentenceSchema).optional(),
})

/** Sentence-layout cards have an open shape (reserved for future use). */
export const SentenceFieldsDataSchema = z.record(z.string(), z.unknown())

/**
 * Wire-format `fields_data` — a union by layout_type. The DB CHECK constraint
 * `cards_fields_data_shape` enforces vocabulary/grammar carry the WordFields
 * keys, so the union is non-discriminated at the JSON level (the discriminator
 * lives on the parent card's `layoutType`).
 */
export const FieldsDataSchema = z.union([
  VocabularyFieldsDataSchema,
  GrammarFieldsDataSchema,
  SentenceFieldsDataSchema,
])
